# Generated by Django 5.1.5 on 2025-02-08 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="purpose",
            new_name="porpose",
        ),
    ]
